services:
  accounts:
    image: "ashok7777/accounts:v1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sevenstack
  cards:
    image: "ashok7777/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sevenstack
  loans:
    image: "ashok7777/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sevenstack
networks:
  sevenstack:
    driver: "bridge"